name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
           
      - name: Install Production Requirements
        run: pip install -r requirements.txt

      - name: Install Development Requirements
        run: pip install -r requirements-dev.txt
      
      - name: Execute tests
        run: task test